import { describe, it, expect, beforeAll, afterAll } from 'vitest'
import { createClient, type SupabaseClient } from '@supabase/supabase-js'
import { prisma } from '@/lib/prisma'
import {
  ensureTestAuthUser,
  getJwtForTestUser,
  cleanupTestAuthUsers,
} from './helpers/test-users'

const SUPABASE_URL      = process.env.NEXT_PUBLIC_SUPABASE_URL!
const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!

const CB1_EMAIL        = 'cb.user@bureauveritas.example.com'
const CB3_EMAIL        = 'test.cb.beta@example.com'
const TEST_PASSWORD    = 'TestPassword123!'
const TEST_FORM_NUMBER = 'TEST-RLS-001'

function makeJwtClient(jwt: string): SupabaseClient {
  return createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${jwt}` } },
    auth:   { autoRefreshToken: false, persistSession: false },
  })
}

let testApplicationId: string
let cb1Client: SupabaseClient
let cb3Client: SupabaseClient

describe('RLS cross-tenant isolation', () => {
  beforeAll(async () => {
    // Preemptive cleanup — handles a previous run that crashed before afterAll
    // could delete the test Application. Must run before AppUser id updates to
    // avoid FK violations on addedById when the PK changes.
    await prisma.application.deleteMany({ where: { formNumber: TEST_FORM_NUMBER } })

    // Ensure Supabase auth users exist for both test accounts
    const cb1AuthId = await ensureTestAuthUser(CB1_EMAIL, TEST_PASSWORD)
    const cb3AuthId = await ensureTestAuthUser(CB3_EMAIL, TEST_PASSWORD)

    // Reconcile AppUser.id with the real Supabase auth UUID so the RLS helpers
    // app.user_role() and app.user_cb_id() resolve correctly via auth.uid().
    // Same pattern as register/actions.ts — seed rows use placeholder UUIDs.
    await prisma.appUser.update({ where: { email: CB1_EMAIL }, data: { id: cb1AuthId } })
    await prisma.appUser.update({ where: { email: CB3_EMAIL }, data: { id: cb3AuthId } })

    // Look up CB #1's generated UUID (cannot be hardcoded — auto-generated by Postgres)
    const cbAlpha = await prisma.cB.findUniqueOrThrow({
      where: { name: 'Bureau Veritas Certification India Pvt. Ltd.' },
    })

    // Look up DroneTech's UUID dynamically. Manufacturer.name is not @unique
    // so findFirstOrThrow is required (findUniqueOrThrow won't compile here).
    const droneTech = await prisma.manufacturer.findFirstOrThrow({
      where: { name: 'DroneTech India Pvt. Ltd.' },
    })

    // Insert the test Application via Prisma (admin connection — bypasses RLS).
    // All NOT NULL columns without defaults are supplied explicitly.
    const app = await prisma.application.create({
      data: {
        formNumber:     TEST_FORM_NUMBER,
        manufacturerId: droneTech.id,
        modelName:      'Test RLS Model',
        cbId:           cbAlpha.id,
        submissionDate: new Date('2026-01-01'),
        addedById:      cb1AuthId,
      },
    })
    testApplicationId = app.id

    // Get JWTs and build per-user Supabase clients (anon key + Bearer token).
    // This is the exact code path a real browser session uses — RLS policies
    // are evaluated under the user's identity, NOT the service role.
    const cb1Jwt = await getJwtForTestUser(CB1_EMAIL, TEST_PASSWORD)
    const cb3Jwt = await getJwtForTestUser(CB3_EMAIL, TEST_PASSWORD)
    cb1Client    = makeJwtClient(cb1Jwt)
    cb3Client    = makeJwtClient(cb3Jwt)
  })

  afterAll(async () => {
    try {
      await prisma.application.deleteMany({ where: { formNumber: TEST_FORM_NUMBER } })
    } finally {
      await cleanupTestAuthUsers([CB1_EMAIL, CB3_EMAIL])
    }
  })

  it('CB#1 user CAN see their own Application (positive)', async () => {
    const { data, error } = await cb1Client
      .from('Application')
      .select('*')
      .eq('id', testApplicationId)

    expect(error).toBeNull()
    expect(data).toHaveLength(1)
  })

  it('CB#3 user CANNOT see CB#1 Application — RLS returns empty, not error (negative)', async () => {
    const { data, error } = await cb3Client
      .from('Application')
      .select('*')
      .eq('id', testApplicationId)

    expect(error).toBeNull()
    expect(data).toHaveLength(0)
  })

  it('CB#3 user sees zero Applications total (reverse isolation)', async () => {
    const { data, error } = await cb3Client
      .from('Application')
      .select('*')

    expect(error).toBeNull()
    expect(data).toHaveLength(0)
  })
})
